### ISSUE TITLE
F1 not working

### ISSUE THREAD

**Issue by Alatarius** [BepInEx/BepInEx.ConfigurationManager#54]
I just installed this on a new system (Win 11) yesterday and the config manager doesn't appear when I press F1. I am not tech savvy so looking at logs is useless for me as I wouldn't know what an error in the logs look like nor where to find them.

This works perfectly on Win 7 but not on my Win 11 system.

**Comment by ManlyMarco** [comment]
Windows version has no effect on whether this will work or not. Most likely something is wrong with your bepinex install, either ask in a dedicated modding community for your game or send the full game output log.

**Comment by hkpD** [comment]
Since one of the recent updates the console is being spammed with the following error:

﻿[Error  : Unity Log] TypeLoadException: Could not resolve type with token 01000070 (from typeref, class/assembly BepInEx.UnityInput, BepInEx, Version=5.4.20.0, Culture=neutral, PublicKeyToken=null)
Stack trace:

This is with the only mods installed being BepInEx and Configuration Manager.
Removing Configuration Manager stops the error.

**Comment by hkpD** [comment]
`[Message:   BepInEx] BepInEx 5.4.19.0 - valheim (9/14/2022 12:56:07 PM)
[Info   :   BepInEx] Running under Unity v2020.3.33.9525882
[Info   :   BepInEx] CLR runtime version: 4.0.30319.42000
[Info   :   BepInEx] Supports SRE: True
[Info   :   BepInEx] System platform: Bits64, Windows
[Message:   BepInEx] Preloader started
[Info   :   BepInEx] Loaded 1 patcher method from [BepInEx.Preloader 5.4.19.0]
[Info   :   BepInEx] Loaded 1 patcher method from [SlimVML.Loader 1.1.0.0]
[Info   :   BepInEx] 2 patcher plugins loaded
[Info   :   BepInEx] Patching [UnityEngine.CoreModule] with [BepInEx.Chainloader]
[Info   :   SlimVML] Loading DLLs from D:\SteamLibrary\steamapps\common\Valheim\InSlimVML\Mods
[Warning:   SlimVML] Skipping 0Harmony.dll since it's in ignore list
[Info   :   SlimVML] Invoking static void SlimAssist.SlimAssist::Main(string[] args)
[Message:   BepInEx] Preloader finished
[Info   :  HarmonyX] ### Harmony id=com.valheim.slim_assist, version=2.9.0.0, location=D:\SteamLibrary\steamapps\common\Valheim\BepInEx\core\0Harmony.dll, env/clr=4.0.30319.42000, platform=Win32NT, ptrsize:runtime/env=8/Bits64, Windows
### Started from void SlimAssist.SlimAssist+<>c::<Main>b__0_0(), location D:\SteamLibrary\steamapps\common\Valheim\InSlimVML\Mods\SlimAssist.dll
### At 2022-09-14 02.16.18
Fossilize INFO: Overriding serialization path: "D:\SteamLibrary\steamapps\shadercache\892970\fozpipelinesv6\steamapprun_pipeline_cache".
Fossilize ERROR: Failed to parse ApplicationInfoFilter, letting recording go through.
[Info   :  HarmonyX] Patching void FejdStartup::Start() with 0 prefixes, 1 postfixes, 0 transpilers, 0 finalizers
1 postfixes:
* static void SlimAssist.SlimAssist+Start_Patch::Postfix(FejdStartup __instance)

[Info   :  HarmonyX] Running ILHook manipulator on void FejdStartup::Start()
[Info   :  HarmonyX] Writing postfixes
[Message:   BepInEx] Chainloader ready
[Message:   BepInEx] Chainloader started
[Info   :   BepInEx] 2 plugins to load
[Warning:   BepInEx] Plugin [Configuration Manager 17.1] targets a wrong version of BepInEx (5.4.20.0) and might not work until you update
[Info   :   BepInEx] Loading [Configuration Manager 17.1]
[Info   :   BepInEx] Loading [Vortex Worlds 1.0.1]
[Error  : Unity Log] MissingMethodException: string Utils.GetSaveDataPath()
Stack trace:
UnityEngine.GameObject:AddComponent(Type)
BepInEx.Bootstrap.Chainloader:Start()
UnityEngine.Application:.cctor()

[Message:   BepInEx] Chainloader startup complete
[Info   : Unity Log] 09/14/2022 14:16:23: Starting to load scene:start

[Error  : Unity Log] TypeLoadException: Could not resolve type with token 01000070 (from typeref, class/assembly BepInEx.UnityInput, BepInEx, Version=5.4.20.0, Culture=neutral, PublicKeyToken=null)
Stack trace:

[Error  : Unity Log] TypeLoadException: Could not resolve type with token 01000070 (from typeref, class/assembly BepInEx.UnityInput, BepInEx, Version=5.4.20.0, Culture=neutral, PublicKeyToken=null)
Stack trace:

[Error  : Unity Log] TypeLoadException: Could not resolve type with token 01000070 (from typeref, class/assembly BepInEx.UnityInput, BepInEx, Version=5.4.20.0, Culture=neutral, PublicKeyToken=null)
Stack trace:

[Error  : Unity Log] TypeLoadException: Could not resolve type with token 01000070 (from typeref, class/assembly BepInEx.UnityInput, BepInEx, Version=5.4.20.0, Culture=neutral, PublicKeyToken=null)
Stack trace:

[Error  : Unity Log] TypeLoadException: Could not resolve type with token 01000070 (from typeref, class/assembly BepInEx.UnityInput, BepInEx, Version=5.4.20.0, Culture=neutral, PublicKeyToken=null)
Stack trace:

[Error  : Unity Log] TypeLoadException: Could not resolve type with token 01000070 (from typeref, class/assembly BepInEx.UnityInput, BepInEx, Version=5.4.20.0, Culture=neutral, PublicKeyToken=null)
Stack trace:

[Warning: Unity Log] Only custom filters can be played. Please add a custom filter or an audioclip to the audiosource (Amb_MainMenu).
[Info   : Unity Log] 09/14/2022 14:16:25: Using environment steamid 892970

[Info   : Unity Log] 09/14/2022 14:16:25: Using steam APPID:892970

Setting breakpad minidump AppID = 892970
SteamInternal_SetMinidumpSteamID:  Caching Steam ID:  xxxxxx [API loaded no]
[Info   : Unity Log] 09/14/2022 14:16:26: Authentication:k_ESteamNetworkingAvailability_Attempting

[Info   : Unity Log] 09/14/2022 14:16:26: Steam initialized, persona:hkpD

[Info   : Unity Log] 09/14/2022 14:16:26: Using default prefs

[Info   : Unity Log] 09/14/2022 14:16:26: Valheim version:0.210.6

[Info   : Unity Log] 09/14/2022 14:16:26: Render threading mode:MultiThreaded

[Warning: Unity Log] 09/14/2022 14:16:26: Missing audio clip in music respawn

[Info   : Unity Log] 09/14/2022 14:16:26: Checking for installed DLCs

[Info   : Unity Log] 09/14/2022 14:16:26: DLC:beta installed:False

[Info   : Unity Log] 09/14/2022 14:16:26: Loaded localization CSV:localization language:English

[Info   : Unity Log] 09/14/2022 14:16:26: Loaded localization CSV:localization_extra language:English

[Info   : Unity Log] 09/14/2022 14:16:26: Loaded localization CSV:localization language:English

[Info   : Unity Log] 09/14/2022 14:16:26: Loaded localization CSV:localization_extra language:English

[Info   : Unity Log] 09/14/2022 14:16:26: Failed to find item prefab odin_hammer

[Info   : Unity Log] 09/14/2022 14:16:26: UI Group status changed Menu = True

[Error  : Unity Log] TypeLoadException: Could not resolve type with token 01000070 (from typeref, class/assembly BepInEx.UnityInput, BepInEx, Version=5.4.20.0, Culture=neutral, PublicKeyToken=null)
Stack trace:

[Error  : Unity Log] TypeLoadException: Could not resolve type with token 01000070 (from typeref, class/assembly BepInEx.UnityInput, BepInEx, Version=5.4.20.0, Culture=neutral, PublicKeyToken=null)
Stack trace:

[Error  : Unity Log] TypeLoadException: Could not resolve type with token 01000070 (from typeref, class/assembly BepInEx.UnityInput, BepInEx, Version=5.4.20.0, Culture=neutral, PublicKeyToken=null)
Stack trace:

[Error  : Unity Log] TypeLoadException: Could not resolve type with token 01000070 (from typeref, class/assembly BepInEx.UnityInput, BepInEx, Version=5.4.20.0, Culture=neutral, PublicKeyToken=null)
Stack trace:

[Error  : Unity Log] TypeLoadException: Could not resolve type with token 01000070 (from typeref, class/assembly BepInEx.UnityInput, BepInEx, Version=5.4.20.0, Culture=neutral, PublicKeyToken=null)
Stack trace:

[Error  : Unity Log] TypeLoadException: Could not resolve type with token 01000070 (from typeref, class/assembly BepInEx.UnityInput, BepInEx, Version=5.4.20.0, Culture=neutral, PublicKeyToken=null)
Stack trace:

[Error  : Unity Log] TypeLoadException: Could not resolve type with token 01000070 (from typeref, class/assembly BepInEx.UnityInput, BepInEx, Version=5.4.20.0, Culture=neutral, PublicKeyToken=null)
Stack trace:

[Error  : Unity Log] TypeLoadException: Could not resolve type with token 01000070 (from typeref, class/assembly BepInEx.UnityInput, BepInEx, Version=5.4.20.0, Culture=neutral, PublicKeyToken=null)
Stack trace:

[Error  : Unity Log] TypeLoadException: Could not resolve type with token 01000070 (from typeref, class/assembly BepInEx.UnityInput, BepInEx, Version=5.4.20.0, Culture=neutral, PublicKeyToken=null)
Stack trace:

[Error  : Unity Log] TypeLoadException: Could not resolve type with token 01000070 (from typeref, class/assembly BepInEx.UnityInput, BepInEx, Version=5.4.20.0, Culture=neutral, PublicKeyToken=null)
Stack trace:

[Error  : Unity Log] TypeLoadException: Could not resolve type with token 01000070 (from typeref, class/assembly BepInEx.UnityInput, BepInEx, Version=5.4.20.0, Culture=neutral, PublicKeyToken=null)
Stack trace:

[Error  : Unity Log] TypeLoadException: Could not resolve type with token 01000070 (from typeref, class/assembly BepInEx.UnityInput, BepInEx, Version=5.4.20.0, Culture=neutral, PublicKeyToken=null)
Stack trace:

[Error  : Unity Log] TypeLoadException: Could not resolve type with token 01000070 (from typeref, class/assembly BepInEx.UnityInput, BepInEx, Version=5.4.20.0, Culture=neutral, PublicKeyToken=null)
Stack trace:

[Error  : Unity Log] TypeLoadException: Could not resolve type with token 01000070 (from typeref, class/assembly BepInEx.UnityInput, BepInEx, Version=5.4.20.0, Culture=neutral, PublicKeyToken=null)
Stack trace:

[Error  : Unity Log] TypeLoadException: Could not resolve type with token 01000070 (from typeref, class/assembly BepInEx.UnityInput, BepInEx, Version=5.4.20.0, Culture=neutral, PublicKeyToken=null)
Stack trace:

[Error  : Unity Log] TypeLoadException: Could not resolve type with token 01000070 (from typeref, class/assembly BepInEx.UnityInput, BepInEx, Version=5.4.20.0, Culture=neutral, PublicKeyToken=null)
Stack trace:

[Error  : Unity Log] TypeLoadException: Could not resolve type with token 01000070 (from typeref, class/assembly BepInEx.UnityInput, BepInEx, Version=5.4.20.0, Culture=neutral, PublicKeyToken=null)
Stack trace:

`

**Comment by ManlyMarco** [comment]
Closing as stale

**Comment by Stroichik** [comment]
i got same issue. F1 not showing Config GUI in game and got lots of red errors. Vortex install .dll into ConfigurationManager folder inside plugins folder.
![image](https://user-images.githubusercontent.com/12185977/209405303-2c38d678-508d-444f-8c22-3de14a6f2d30.png)

But even if i move dll manually to plugins folder nothing changes.
![image](https://user-images.githubusercontent.com/12185977/209405443-95098faa-c0bf-4eff-8e1f-b914f8a128a7.png)


[LogOutput.log](https://github.com/BepInEx/BepInEx.ConfigurationManager/files/10297334/LogOutput.log)

**Comment by ManlyMarco** [comment]
@Stroichik Update BepInEx to latest version. Please ask on the valheim discord server for further help.

**Comment by Stroichik** [comment]
Yeah, thx. I figured it out already about vesions. it was not too obvious, since its Vortex that automatically downloads both Bepinex + ConfigMenu, but it downloads Bepinex 5.4.19 and ConfigMenu 17.1.0. It wasn't like that 6 months ago since i played last time, so i wasn't sure whats wrong. Downgrading CM to 17.0 worked for me.
