### ISSUE TITLE
KK_CyuVR can not work since v17.0

### ISSUE THREAD

**Issue by magicdolls** [BepInEx/BepInEx.ConfigurationManager#58]
When I update my ConfigurationManager in to v17, I found that CyuVR can not work and when I go back to v16.4 it can working.
I think CyuVR is a good plug for vr player, coud you do something to support it in the next version?

**Comment by magicdolls** [comment]
this is the webset of cyuvr, it is an old plug but it is really nice one.
https://github.com/MayouKurayami/KK_CyuVR

**Comment by ManlyMarco** [comment]
Obsolete APIs were removed as planned, so this is not going to be changed. CyuVR will have to be updated to make it work with the latest version.

**Comment by NovNovikov** [comment]
How they are obsolete is they are used by some plugins? Never understood this cancer logic to remove something that other stuff already depends on.

**Comment by ManlyMarco** [comment]
Because it's an unnecessary baggage that causes increasingly more issues as things move on, and pretty much no plugins rely on the obsoleted members by now. If a plugin is old enough to require the obsoleted members that got removed then it's probably going to have other compatibility issues too. It's up on github so anyone could just fork it and update it.
